# Generated by Django 2.2.4 on 2019-08-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('tipo', models.CharField(blank=True, choices=[('FR', 'camisa'), ('SO', 'camiseta'), ('JR', 'pantalon'), ('SR', 'calzado')], default=None, max_length=200, null=True)),
            ],
        ),
    ]
