# Generated by Django 3.0.4 on 2020-06-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenda', '0007_voto_usuario'),
        ('usuario', '0003_auto_20200609_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='prendas',
            field=models.ManyToManyField(blank=True, related_name='prendas_usuario', to='prenda.Prenda'),
        ),
    ]
