# Generated by Django 3.0.4 on 2020-04-10 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('tipo', models.CharField(blank=True, choices=[('camisa', 'camisa'), ('camiseta', 'camiseta'), ('pantalon', 'pantalon'), ('calzado', 'calzado')], default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positivos', models.IntegerField(default=0)),
                ('negativos', models.IntegerField(default=0)),
                ('neutrales', models.IntegerField(default=0)),
                ('prenda_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenda_1', to='prenda.Prenda')),
                ('prenda_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenda_2', to='prenda.Prenda')),
            ],
        ),
    ]
