# Generated by Django 3.0.4 on 2020-04-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenda', '0003_auto_20200413_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenda',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
    ]
