# Generated by Django 3.0.4 on 2020-05-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenda', '0004_auto_20200413_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='porcentaje_like',
            field=models.IntegerField(default=0),
        ),
    ]
