# Generated by Django 3.0.4 on 2020-05-06 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prenda', '0005_match_porcentaje_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veredicto', models.CharField(choices=[(1, 'positivo'), (0, 'neutral'), (-1, 'negativo')], max_length=20)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prenda.Match')),
            ],
        ),
    ]
