# Generated by Django 3.0.4 on 2020-05-06 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('prenda', '0006_voto'),
    ]

    operations = [
        migrations.AddField(
            model_name='voto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario'),
        ),
    ]
